on:
  push:
    branches: [master]
    paths:
      - '**.sh'
      - '.github/workflows/**'
  schedule:
    - cron: "4 2 * * *"
  workflow_dispatch: ~

name: Release

concurrency:
  group: release
  cancel-in-progress: true

permissions:
  contents: write

env:
  RELEASE_NAME: experimental
  PKGBUILD_SHA256SUM: "3bcb02105c58946eb0c717cd5d853bd13fca6815249b1ec9b6ce9796d09a7d7b"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: sudo apt install -y makepkg pacman-package-manager
      - name: Prepare build
        run: ./prepare_build_test.sh
      - name: Build packages
        run: docker run -e EXPORT_PKG=true -e CHECKSUM_SRC=false -v "./build:/pkg" ghcr.io/zaggash/arch-makepkg:latest
      - name: Debug check build folder again
        run: ls ./build
      # - name: Create artifact to test the package
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: ./build
      #     overwrite: true
      - name: Release packages
        uses: ncipollo/release-action@v1.16.0
        with:
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.RELEASE_NAME }}
          commit: ${{ github.sha }}
          artifacts: ./build/*.tar.zst
          allowUpdates: true
          artifactErrorsFailBuild: true
          omitBody: true
          omitBodyDuringUpdate: true
          removeArtifacts: true
